easy_admin:
    site_name: Base de Datos de Conciliaciones

    design:
        menu:
            - { route: 'inicio', label: 'Inicio', icon: 'home' }
            - { entity: 'Departamento', label: 'Departamento', icon: 'map-marker' }
            - { entity: 'Centro', label: 'Centro', icon: 'map-marker' }
            - { entity: 'Reporte', label: 'Reporte', icon: 'file' }
            - { entity: 'Usuario', label: 'Usuarios', icon: 'user' }

    entities:
        Departamento:
            class: App\Entity\Departamento

        Localidad:
            class: App\Entity\Localidad

        Reporte:
            class: App\Entity\Reporte

            list:
                fields:
                    - { property: 'centro'}
                    - { property: 'gestion' }
                    - { property: 'acta' }
                    - { property: 'virtual' }
                    - { property: 'fileReporte', type: 'image', 'base_path': "/uploads/files", label: 'Archivo' }
                sort: ['centro', 'ASC']
                filters: ['centro']


        Centro:
            class: App\Entity\Centro

            list:
                fields:
                    - { property: 'nombreCentro' }
                    - { property: 'matricula', type: 'text' }
                    #- { property: 'resolucion', type: 'text' }
                    - { property: 'inicioVigencia', type: 'date' }
                    - { property: 'finVigencia', type: 'date' }
                    - { property: 'nombreCentro', type: 'text' }
                    - { property: 'representante', type: 'text' }
                    - { property: 'cargo', type: text }
                    - { property: 'dpto' }
                    #- { property: 'zona', type: 'text' }
                    #- { property: 'direccion', type: 'text' }
                    - { property: 'telefono', type: 'text' }
                    #- { property: 'fax', type: 'integer' }
                    - { property: 'correo', type: 'email' }
                sort: [ 'nombreCentro', 'ASC' ]
                filters: [ 'dpto' ]

            edit:
                fields:
                    - { property: 'nombreCentro' }
                    - { property: 'matricula', type: 'text' }
                    - { property: 'resolucion', type: 'text' }
                    - { property: 'inicioVigencia', type: 'date' }
                    - { property: 'finVigencia', type: 'date' }
                    - { property: 'nombreCentro', type: 'text' }
                    - { property: 'representante', type: 'text' }
                    - { property: 'cargo', type: 'text' }
                    - { property: 'dpto' }
                    - { property: 'zona', type: 'text' }
                    - { property: 'direccion', type: 'text' }
                    - { property: 'telefono', type: 'integer' }
                    - { property: 'fax', type: 'integer' }
                    - { property: 'correo', type: 'email' }

        # List the entity class name you want to manage
        #- App\Entity\Materia
        #- App\Entity\Edad

        Usuario:
            class: App\Entity\Usuario

            list:
                fields:
                    - { property: 'nombre' }
                    - { property: 'primerApellido' }
                    - { property: 'segundoApellido' }
                    - { property: 'username' }
                    - { property: 'password' }
                    - { property: 'roles' }

            new:
                fields:
                    - { property: 'nombre' }
                    - { property: 'username' }
                    - { property: 'password' }
                    #- { property: 'roles', }
                    - { property: 'primerApellido' }
                    - { property: 'segundoApellido' }